### PR TITLE
PR to fix the issue with newer firmwares on CM1000 modems

### LINKED ISSUE #4: Broken with firmware update...but...I've fixed it.
This is broken by the latest firmware update for the CM1100 modem. Mediacom cable randomly upgraded me from V2.01.02 to V7.01.01.
The login method switches from http basic auth to an html form.

I've already fixed this in my local fork, but it needs to be polished a bit before I submit a PR.
My version uses environmental variables to pass it the InfluxDB info and user/pass. I'll add a way to specify which version of auth is required for someone's particular modem.

### PR DESCRIPTION
**Pull request by ancker010**
Fixes #4 

A bunch of changes here.
Pretty self explanatory. 
- Changed to a bunch of environment variables.
- Made modem auth configurable based on firmware
- Added docker-compose.yml file

### CODE REVIEW

**Comment by ancker010** [comment]
This PR should fix #4

**Comment by iandees** [comment]
Looks great, thank you!

**Comment by ancker010** [comment]
Crap, I missed a space in the `docker build` command in the README. Can you fix adding a space before the '.'?

**Comment by iandees** [comment]
Done in f61b085. Thanks for spotting that.

**Pull request merged**
